pipeline {
  agent {
    docker {
      image 'node:16'  // hoặc node:18, node:20 tuỳ version bạn cần
      args '-u root:root'  // nếu cần quyền root để cài thêm
    }
  }

  environment {
    DOCKERHUB_CREDENTIALS = credentials('dockerhub-cred-id')
    DOCKERHUB_USERNAME = 'khangdinh2103'
    FE_IMAGE = "${DOCKERHUB_USERNAME}/jewelry-fe"
  }

  stages {
    stage('Checkout Frontend') {
      steps {
        git 'https://github.com/khangdinh2103/Microservices_Jewelry_eCommerce_FE'
      }
    }

    stage('Build Frontend') {
      steps {
        sh 'npm install'
        sh 'npm run build'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh "docker build -t ${FE_IMAGE}:latest ."
      }
    }

    stage('Push to Docker Hub') {
      steps {
        script {
          docker.withRegistry('https://index.docker.io/v1/', DOCKERHUB_CREDENTIALS) {
            sh "docker push ${FE_IMAGE}:latest"
          }
        }
      }
    }
  }
}
